
FIND_PATH(HDFS_INCLUDES hdfs.h
  HINTS
  ${HDFS_INCLUDE_DIR}
  $ENV{HDFS_INCLUDE_DIR}
  /usr
  PATH_SUFFIXES include
)

FIND_LIBRARY(HDFS_LIB hdfs
  HINTS
  ${HDFS_LIB_DIR}
  $ENV{HDFS_LIB_DIR}
  /usr
  PATH_SUFFIXES lib
)

GET_FILENAME_COMPONENT(HDFS_LIB_DIR ${HDFS_LIB} PATH)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Hdfs DEFAULT_MSG HDFS_LIB HDFS_LIB_DIR HDFS_INCLUDES)

